<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Steamless.Unpacker.Variant10.x86</RootNamespace>
    <AssemblyName>Steamless.Unpacker.Variant10.x86</AssemblyName>
    <Description>Steamless SteamStub Variant v1.0 (x86) Unpacker</Description>
    <Platforms>x86</Platforms>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Steamless.API\Steamless.API.csproj" />
  </ItemGroup>
</Project>