<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Steamless.Unpacker.Variant20.x86</RootNamespace>
    <AssemblyName>Steamless.Unpacker.Variant20.x86</AssemblyName>
    <Description>Steamless SteamStub Variant v2.0 (x86) Unpacker</Description>
    <Platforms>x86</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>..\Steamless\bin\x86\Debug\Plugins\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>..\Steamless\bin\x86\Release\Plugins\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iced" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Steamless.API\Steamless.API.csproj" />
  </ItemGroup>
</Project>